version: 3.9
services:
  web:
    image: "nginx:alpine"
    ports:
      - 8088:80
    volumes:
      - webdata:/var/www/html
    networks:
      - frontend
  proxy-sensor:
    image: "hoho/sensor-http-proxy:latest"
    environment:
      HOHO_PACK_ID: example-wp-stack
      HOHO_STORAGE_BACKEND: filesystem
      HOHO_STORAGE_ROOT: /artifacts
    volumes:
      - artifacts:/artifacts
  fsmon-sensor:
    image: "hoho/sensor-fsmon:latest"
    environment:
      HOHO_PACK_ID: example-wp-stack
      HOHO_STORAGE_BACKEND: filesystem
      HOHO_STORAGE_ROOT: /artifacts
    volumes:
      - artifacts:/artifacts
  pcap-sensor:
    image: "hoho/sensor-pcap:latest"
    environment:
      HOHO_PACK_ID: example-wp-stack
      HOHO_STORAGE_BACKEND: filesystem
      HOHO_STORAGE_ROOT: /artifacts
    volumes:
      - artifacts:/artifacts
volumes:
  artifacts:

